TEST_VALUE:
  name: "dev_cookie"

FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a38f056692e2900b
  FEISHU_APP_SECRET: Yc8HQA8dDtNLYQ8nnV0E97ELWF0d6svw

APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY